#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/usuario/Simics/simics-6.0.185"
export SIMICS_BASE_PACKAGE
if [ -f "/home/usuario/Documents/Empotrados-2Project/simics-project/.package-list" ]; then
    exec "/home/usuario/Simics/simics-6.0.185/bin/simics-eclipse" --package-list "/home/usuario/Documents/Empotrados-2Project/simics-project/.package-list" --project "/home/usuario/Documents/Empotrados-2Project/simics-project" "$@"
else
    exec "/home/usuario/Simics/simics-6.0.185/bin/simics-eclipse" --project "/home/usuario/Documents/Empotrados-2Project/simics-project" "$@"
fi
